### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by blogclub** [ahmedrangel/animed#2]
Hello, I like your project very much. Does this project have any plans to play videos instead of jumping to crunchyroll to watch?

**Comment by ahmedrangel** [comment]
> Hello, I like your project very much. Does this project have any plans to play videos instead of jumping to crunchyroll to watch?

Thanks, but I'm not planning to do it because it could infringe copyrights.

For this project, I mainly focused on listing anime using data provided by the Anilist API but not as a video streaming platform.

**Comment by ahmedrangel** [comment]
> Hello, I like your project very much. Does this project have any plans to play videos instead of jumping to crunchyroll to watch?

Thanks, but I'm not planning to do it because it could infringe copyrights.

For this project, I mainly focused on listing anime using data provided by the Anilist API but not as a video streaming platform.

But in the medium/long term, I plan to add user functions such as saving to favorites, creating your watchlist, watching status/progress, etc.
